### ISSUE TITLE
core_articles() (always) returns empty `$data$duplicates` list

### ISSUE THREAD

**Issue by mstbr** [ropensci/rcoreoa#22]
```
tmp <- core_articles(some_id, duplicate = TRUE)
```
I have tried with a sample of 100 IDs which contains very obvious candidates to be flagged as duplicates by the CORE API's /articles/dedup method, but they all return with an empty `duplicates` list.

My apologies if this is only because of my unlucky sample and if other IDs will, in fact, return duplicate info.

**Comment by sckott** [comment]
thanks, i'll take a loook

**Comment by sckott** [comment]
you'll need to share a reproducible example of the error

**Comment by mstbr** [comment]
No problem, sorry for not already having done so.
I assume the three articles below should be identified as duplicates (at least, their abstracts are identical). The `duplicates` lists are empty, however.
I hope this helps.

```
library(rcoreoa)

dupe_ids <- c("47777837", "51233178", "52907795")

dupe_check <- lapply(dupe_ids, core_articles, duplicate = TRUE)

dupe_titles <- c(
  dupe_check[[1]][[2]][["title"]],
  dupe_check[[2]][[2]][["title"]],
  dupe_check[[3]][[2]][["title"]]
)

dupe_info <- c(dupe_check[[1]][[2]]["duplicates"],
               dupe_check[[2]][[2]]["duplicates"],
               dupe_check[[3]][[2]]["duplicates"])

length(unique(dupe_titles))
dupe_info
```

**Comment by sckott** [comment]
thanks, I can confirm I get the same thing. 

I've no idea what's going on. I've emailed them to see if we can get this sorted out, will let you know what I found out

**Comment by sckott** [comment]
Still no response from them. I doubt we'll ever get one unfortunately

**Comment by mstbr** [comment]
Too bad! But many thanks for trying and your great work on these packages in general 👍🏻 It's very much appreciated.

**Comment by sckott** [comment]
@mstbr actually just heard back. they said it should be fixed now. they also said to note that:

> `/articles/get/{coreId}` uses title based duplicate detection while /articles/dedup provides more options for near duplicates detection.

`/articles/get/{coreId}` is the API route that `core_articles()` uses - the `/articles/dedup` we don't have a function for yet - making that now

**Comment by sckott** [comment]
added a fxn `core_articles_dedup()` for that dedup route

**Comment by sckott** [comment]
@mstbr CORE has fixed the dedup API route, give `core_articles_dedup()` a try if you have time

**Comment by sckott** [comment]
duplicates in `core_articles` is working now
