### ISSUE TITLE
Support for formulation of advanced search requests

### ISSUE THREAD

**Issue by aristotelisxs** [ropensci/rcoreoa#4]
While the search endpoint can already accept correctly formed advanced searching in string format, the need for either another endpoint or the extension of the existing endpoint to offer advanced query builder options would be a nice addition to the project.

Currently, CORE's API does not have similar support for this either and I can see why it was not considered for this project until now, but this would allow for a more drilled-down look into CORE's data with little effort from library users.

I suggest that the search endpoint should be extended to accept a named list in the place of "query" with the parameters below if an advanced query needs to be constructed.

<img width="1146" alt="screen shot 2017-04-21 at 10 27 13" src="https://cloud.githubusercontent.com/assets/10947799/25271749/20596364-267d-11e7-8e2a-72b79dfaaa03.png">

**Comment by sckott** [comment]
By _search endpoint_ you're talking about the CORE API, yes? not the `core_search` function in this pkg?

I agree, makes sense - you're suggesting we ask CORE team to support this?

**Comment by aristotelisxs** [comment]
Yes, CORE's API is missing a direct link to advanced searches, even if it is supported by its search endpoint.

I forgot to mention earlier that I actually work for CORE and what we can do to, kind of, bypass the need for any work on the CORE API is build helper functions within the cored package here to support the formulation of advanced queries, as they are currently parsed through CORE's search endpoint anyway.

I have started "translating" the parsing process from CORE to R here for this purpose, and was looking to see if you would agree to a pull request on this before I finish any implementation!

What do you think?

**Comment by sckott** [comment]
Cool, i thought you might work for CORE

> I have started "translating" the parsing process from CORE to R here for this purpose, and was looking to see if you would agree to a pull request on this before I finish any implementation!

yes, sounds good!

**Comment by sckott** [comment]
fixed via #6
