### ISSUE TITLE
core_articles_pdf() --> Error : "not found (HTTP 404)"

### ISSUE THREAD

**Issue by YoelisA** [ropensci/rcoreoa#9]
I would like to download the full pdf text of an article :

```r
query <- data.frame("all_of_the_words" = "data mining",
                                         "without_the_words" = "social science",
                                         "year_from" = "2013",
                                         "year_to" = "2014")
result <- core_advanced_search(query, key = key)
core_articles_pdf_(result$data$id[1], key = key)
```

As a result I get : `Error : "not found (HTTP 404)`

<img width="466" alt="capture d ecran 2017-11-23 a 14 08 01" src="https://user-images.githubusercontent.com/33930562/33174894-279eadbe-d05a-11e7-8c6b-430b01c8637a.png">

I can't access the full text of any of the articles IDs I tried, even through the function 'core_articles()'.

```r
> tdq$data$fullText
[1] ""'
```

I also tried to get the full text directly from the API but I still get this HTTP 404 error

<img width="908" alt="capture d ecran 2017-11-23 a 14 23 57" src="https://user-images.githubusercontent.com/33930562/33174873-13319a12-d05a-11e7-98fb-90fd7e13717c.png">

Any solutions ? 

Regards

**Comment by sckott** [comment]
thanks for the report @YoelisA - looking into it

**Comment by sckott** [comment]
( @YoelisA you should get a new API key if that is your API key above in the screenshot :)  )

**Comment by YoelisA** [comment]
@sckott  key is just the variable which contains the actual API key :)

**Comment by sckott** [comment]
the screenshot, not the text based code snippet

**Comment by YoelisA** [comment]
Directly with the actual API key :) 

I think it works because I can use all the functions but still this issue with the fulltext access...

**Comment by sckott** [comment]
Sorry, i guess i'm not getting the point across. Since your API key is exposed here to the public, others can now potentially use your API key.  Does that make sense?  Therefore, I suggest getting a new one which makes the old one exposed here invalid.

**Comment by YoelisA** [comment]
Oh right, I wasn't looking at the good screenshot, the API was in clear within the url... I thought you had doubts about the integrity of the API key. I'll ask for another one. Sorry !

**Comment by sckott** [comment]
So not all article records found in CORE have PDFs associated with them it turns out. I updated the documentation to discuss more what the 404 message means:

> If you get a message like `Error: Not Found (HTTP 404)`, that means
a PDF was not found. That is, it does not exist. That is, there is no
PDF associated with the article ID you searched for. This is the
correct behavior, and nothing is wrong with this function or this
package. We could do another web request to check if the id you
pass in has a PDF or not first, but that's another request, slowing
this function down.
